1 .Zero exception

#include <iostream>

using namespace std;

int main()
{ int d, n1 , n2;
cin>>n1;
cin>>n2;
try 
{
    if (n2==0){
        throw runtime_error("Math error:Attempted to divide by zero");
    }
    else{cout<<n2;}
}
catch (runtime_error& e) {
    cout<<"Exception occurred "<<endl<<e.what();
}
d = n1/n2;
cout<<"The division is "<<d<<endl;

return 0;
}

-----------------------------------------------------------------------------------------------------------------------------------------------------------

2 . out of bound array access

#include <iostream>
# define size 10
using namespace std;

int main()
{
    int A[size];
    try
    { for(int i =0 ; i<=size; i++)
      {  if(i>size-1){
          throw "Out of range";
          A[size]='z';
      }
      }
    }
      catch (char * str)
      {cout<<"Exception:"<<str<<endl;
      }
      return 0;
    }

-----------------------------------------------------------------------------------------------------------------------------------------------------------